#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - ca-certificates
  - curl
  - gnupg

runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com | sh

  # Enable & start Docker
  - systemctl enable docker
  - systemctl start docker

  # Add user to docker group
  - usermod -aG docker azureadmin

  # Install Docker Compose v2
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
    -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
